steps:
  # Build the container image from the backend directory
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-istanbul-backend:$COMMIT_SHA'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend/'
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ai-istanbul-backend:$COMMIT_SHA'
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-stanbul'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-istanbul-backend:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DATABASE_URL=postgresql://postgres:%2AiwP%23MDmX5dn8V%3A1LExE%7C70%3AO%3E%7Ci@database-1.cleeowy8eb7v.eu-central-1.rds.amazonaws.com:5432/postgres?sslmode=require,PURE_LLM_MODE=true,GOOGLE_MAPS_API_KEY=AIzaSyDiQjBfo7Lk9WOL7ut4wbiNbNWQpgr1k9Q,GOOGLE_PLACES_API_KEY=AIzaSyDiQjBfo7Lk9WOL7ut4wbiNbNWQpgr1k9Q,OPENWEATHER_API_KEY=49575391e412bd4332062ffdb688c38c,LLM_API_URL=https://4r1su4zfuok0s7-8000.proxy.runpod.net/v1,LLM_MODEL_NAME=/workspace/Meta-Llama-3.1-8B-Instruct-AWQ-INT4,SECRET_KEY=Ozw5vFR0HzgXPPtNk1DdZwCfRL7Dl6HwGe_m0CN_zfg,ENVIRONMENT=production,DEBUG=false'
      - '--timeout'
      - '300'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/ai-istanbul-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
