steps:
  # Build the container image using root Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ai-stanbul:$BUILD_ID'
      - '-f'
      - 'Dockerfile'
      - '.'
    
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ai-stanbul:$BUILD_ID'
    
  # Deploy container image to Cloud Run with ALL fixes
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-stanbul'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ai-stanbul:$BUILD_ID'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      # VPC Connectivity Configuration (CRITICAL FOR REDIS/POSTGRES)
      - '--vpc-connector'
      - 'ai-istanbul-connector'
      - '--vpc-egress'
      - 'all-traffic'
      # Environment Variables - COMPLETE LIST
      - '--set-env-vars'
      - 'DATABASE_URL=postgresql://postgres:Yeniden.1881@34.38.193.1:5432/postgres,REDIS_URL=redis://ai-istanbul-cache:AiIstanbul2025%21Redis%23Secure%24@3.126.153.140:6379,ENABLE_REDIS_CACHE=true,REDIS_SOCKET_TIMEOUT=2,REDIS_SOCKET_CONNECT_TIMEOUT=2,ENVIRONMENT=production,LLM_API_URL=https://p9lf44wbmqzs5l-8000.proxy.runpod.net/v1,LLM_MODEL_NAME=meta-llama/Meta-Llama-3.1-8B-Instruct,LLM_TIMEOUT=120,LLM_MAX_TOKENS=768,PYTHONUNBUFFERED=1,TOKENIZERS_PARALLELISM=false'
      # Resource Configuration
      - '--timeout'
      - '300'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/ai-istanbul-backend:$BUILD_ID'

options:
  logging: CLOUD_LOGGING_ONLY
