services:
  - type: web
    name: ai-stanbul-backend
    env: python
    buildCommand: "pip install -r requirements-minimal.txt"
    startCommand: "./start-render.sh"
    envVars:
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false  # This tells Render to get the value from the dashboard
    healthCheckPath: /
