services:
  - type: web
    name: ai-istanbul-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: GOOGLE_WEATHER_API_KEY
        sync: false
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: GOOGLE_ANALYTICS_PROPERTY_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health
    scaling:
      minInstances: 1
      maxInstances: 3
