global:
  evaluation_interval: 15s
  scrape_interval: 15s
rule_files:
- alert_rules.yml
scrape_configs:
- job_name: istanbul-ai
  metrics_path: /metrics
  scrape_interval: 10s
  static_configs:
  - targets:
    - istanbul-ai:8080
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
