"""Initial migration

Revision ID: 8017f37ca05c
Revises: 
Create Date: 2025-09-20 15:21:21.836221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8017f37ca05c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transport_routes_id'), table_name='transport_routes')
    op.drop_index(op.f('ix_transport_routes_route_name'), table_name='transport_routes')
    op.drop_table('transport_routes')
    op.drop_index(op.f('ix_turkish_phrases_id'), table_name='turkish_phrases')
    op.drop_table('turkish_phrases')
    op.drop_index(op.f('ix_local_tips_id'), table_name='local_tips')
    op.drop_table('local_tips')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_session_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=True),
    sa.Column('dietary_restrictions', sa.VARCHAR(), nullable=True),
    sa.Column('accommodation_district', sa.VARCHAR(), nullable=True),
    sa.Column('days_remaining', sa.INTEGER(), nullable=True),
    sa.Column('budget_level', sa.VARCHAR(), nullable=True),
    sa.Column('interests', sa.TEXT(), nullable=True),
    sa.Column('language_preference', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_session_id'), 'user_profiles', ['session_id'], unique=1)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('local_tips',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('tip_title', sa.VARCHAR(), nullable=True),
    sa.Column('tip_content', sa.TEXT(), nullable=True),
    sa.Column('importance_level', sa.VARCHAR(), nullable=True),
    sa.Column('relevant_districts', sa.VARCHAR(), nullable=True),
    sa.Column('is_offline_available', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_local_tips_id'), 'local_tips', ['id'], unique=False)
    op.create_table('turkish_phrases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('english_phrase', sa.VARCHAR(), nullable=True),
    sa.Column('turkish_phrase', sa.VARCHAR(), nullable=True),
    sa.Column('pronunciation', sa.VARCHAR(), nullable=True),
    sa.Column('context', sa.VARCHAR(), nullable=True),
    sa.Column('audio_file', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turkish_phrases_id'), 'turkish_phrases', ['id'], unique=False)
    op.create_table('transport_routes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('route_name', sa.VARCHAR(), nullable=True),
    sa.Column('transport_type', sa.VARCHAR(), nullable=True),
    sa.Column('from_location', sa.VARCHAR(), nullable=True),
    sa.Column('to_location', sa.VARCHAR(), nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), nullable=True),
    sa.Column('frequency_minutes', sa.INTEGER(), nullable=True),
    sa.Column('first_departure', sa.TIME(), nullable=True),
    sa.Column('last_departure', sa.TIME(), nullable=True),
    sa.Column('price_try', sa.FLOAT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transport_routes_route_name'), 'transport_routes', ['route_name'], unique=False)
    op.create_index(op.f('ix_transport_routes_id'), 'transport_routes', ['id'], unique=False)
    # ### end Alembic commands ###
