"""
Enhanced Training Data Addition Script
Adds 550+ new samples for underrepresented intents:
- Local Tips: 200+ samples
- Hidden Gems: 100+ samples  
- Events: 150+ samples
- Neighborhoods: 100+ samples (new intent)
"""

import json
from pathlib import Path
from collections import Counter


def get_new_local_tips_samples():
    """200+ samples for Local Tips intent"""
    return [
        # Transportation tips (40 samples)
        ["İstanbulkart nereden alınır", "local_tips"],
        ["Toplu taşımada para biriktirme yolları", "local_tips"],
        ["Metrobüs kullanma ipuçları", "local_tips"],
        ["İstanbul'da trafik saatleri ne zaman", "local_tips"],
        ["En ucuz taksi uygulaması hangisi", "local_tips"],
        ["How to buy an Istanbulkart", "local_tips"],
        ["Best time to avoid traffic", "local_tips"],
        ["Metro system tips for tourists", "local_tips"],
        ["Cheap transportation options", "local_tips"],
        ["Ferry schedule tricks", "local_tips"],
        ["Marmaray kullanımı kolay mı", "local_tips"],
        ["Havalimanından şehir merkezine ucuz ulaşım", "local_tips"],
        ["Akbil vs İstanbulkart", "local_tips"],
        ["Gece otobüsleri hangi saatlerde", "local_tips"],
        ["Dolmuş kullanma rehberi", "local_tips"],
        ["Best metro routes for tourists", "local_tips"],
        ["How to navigate the tram system", "local_tips"],
        ["Taxi scam prevention tips", "local_tips"],
        ["Airport shuttle vs private transfer", "local_tips"],
        ["Night transportation options", "local_tips"],
        ["Boğaz geçişi en ucuz nasıl", "local_tips"],
        ["Funicular kullanımı nasıl", "local_tips"],
        ["Teleferik bilet fiyatları", "local_tips"],
        ["Deniz otobüsü indirimleri var mı", "local_tips"],
        ["Öğrenci indirimi nasıl alınır", "local_tips"],
        ["Rush hour avoidance strategies", "local_tips"],
        ["Best transport card deals", "local_tips"],
        ["Cable car operating hours", "local_tips"],
        ["Sea bus discounts available", "local_tips"],
        ["Student discount application", "local_tips"],
        ["Vapur hattı kestirmeler", "local_tips"],
        ["En hızlı Kadıköy-Beşiktaş yolu", "local_tips"],
        ["Metrobüs yoğun saatleri", "local_tips"],
        ["İETT otobüs uygulama tavsiyeleri", "local_tips"],
        ["Toplu taşıma kombinasyonları", "local_tips"],
        ["Ferry line shortcuts", "local_tips"],
        ["Fastest Kadikoy-Besiktas route", "local_tips"],
        ["Metrobus peak hours", "local_tips"],
        ["Bus app recommendations", "local_tips"],
        ["Public transport combinations", "local_tips"],
        
        # Food & dining tips (40 samples)
        ["İstanbul'da kahvaltı nerede yapılır", "local_tips"],
        ["En iyi simit nerede bulunur", "local_tips"],
        ["Balık ekmek hangi vapur iskelesinde", "local_tips"],
        ["Lokanta vs restoran farkı", "local_tips"],
        ["Çay bahçesi önerileri", "local_tips"],
        ["Where to have Turkish breakfast", "local_tips"],
        ["Best place for simit", "local_tips"],
        ["Fish sandwich location tips", "local_tips"],
        ["Cheap lunch spots locals love", "local_tips"],
        ["Tea garden recommendations", "local_tips"],
        ["Sokak lezzeti güvenli mi", "local_tips"],
        ["Taze balık nasıl anlaşılır", "local_tips"],
        ["Kebapçı seçimi ipuçları", "local_tips"],
        ["Meyhane kültürü nasıl yaşanır", "local_tips"],
        ["Pidecide ne sipariş edilir", "local_tips"],
        ["Is street food safe to eat", "local_tips"],
        ["How to tell fresh fish", "local_tips"],
        ["Kebab restaurant selection tips", "local_tips"],
        ["Meyhane culture explained", "local_tips"],
        ["What to order at pide place", "local_tips"],
        ["Köfteci fiyat karşılaştırması", "local_tips"],
        ["En ekonomik yemek nerede", "local_tips"],
        ["Sahil restoranları fiyat ipuçları", "local_tips"],
        ["Tatlıcı seçimi nasıl yapılır", "local_tips"],
        ["Dönerci kalite kriterleri", "local_tips"],
        ["Meatball restaurant price comparison", "local_tips"],
        ["Most economical meal spots", "local_tips"],
        ["Seaside restaurant pricing tips", "local_tips"],
        ["Dessert shop selection guide", "local_tips"],
        ["Doner quality criteria", "local_tips"],
        ["Mantı nerede yenir", "local_tips"],
        ["Kokoreç güvenli mekanlar", "local_tips"],
        ["Kumpir en iyisi nerede", "local_tips"],
        ["Midye dolma hijyen ipuçları", "local_tips"],
        ["Islak hamburger nerede", "local_tips"],
        ["Where to eat manti dumplings", "local_tips"],
        ["Safe places for kokorec", "local_tips"],
        ["Best kumpir location", "local_tips"],
        ["Stuffed mussels hygiene tips", "local_tips"],
        ["Where to find wet hamburgers", "local_tips"],
        
        # Shopping tips (40 samples)
        ["Çarşıda pazarlık nasıl yapılır", "local_tips"],
        ["Sahte ürün nasıl anlaşılır", "local_tips"],
        ["En ucuz alışveriş günü hangisi", "local_tips"],
        ["Outlet merkezler nerede", "local_tips"],
        ["Yerel pazar günleri", "local_tips"],
        ["How to bargain in bazaar", "local_tips"],
        ["Fake product detection tips", "local_tips"],
        ["Cheapest shopping day", "local_tips"],
        ["Outlet mall locations", "local_tips"],
        ["Local market schedule", "local_tips"],
        ["Altın alırken dikkat edilecekler", "local_tips"],
        ["Halı seçimi püf noktaları", "local_tips"],
        ["Baharat çarşısı fiyat taktikleri", "local_tips"],
        ["Deri ürün kalite testi", "local_tips"],
        ["Çini seramik orijinal nasıl anlaşılır", "local_tips"],
        ["Gold buying precautions", "local_tips"],
        ["Carpet selection secrets", "local_tips"],
        ["Spice bazaar pricing tactics", "local_tips"],
        ["Leather quality test", "local_tips"],
        ["Authentic tile ceramic identification", "local_tips"],
        ["Turistik esnaf vs yerli esnaf", "local_tips"],
        ["İndirim sezonları ne zaman", "local_tips"],
        ["Vergi iadesi nasıl alınır", "local_tips"],
        ["AVM kart avantajları", "local_tips"],
        ["Online vs mağaza fiyat farkı", "local_tips"],
        ["Tourist shops vs local shops", "local_tips"],
        ["When are discount seasons", "local_tips"],
        ["How to get tax refund", "local_tips"],
        ["Mall card advantages", "local_tips"],
        ["Online vs store price difference", "local_tips"],
        ["Sahaf kitap alırken dikkat", "local_tips"],
        ["Antika pazar ipuçları", "local_tips"],
        ["El işi ürün fiyat kontrolü", "local_tips"],
        ["Tekstil toptancıları nerede", "local_tips"],
        ["Teknoloji alışverişi öneriler", "local_tips"],
        ["Second-hand bookshop caution", "local_tips"],
        ["Antique market tips", "local_tips"],
        ["Handcraft product pricing", "local_tips"],
        ["Textile wholesale locations", "local_tips"],
        ["Electronics shopping advice", "local_tips"],
        
        # Cultural & etiquette tips (40 samples)
        ["Camii ziyareti kıyafet kuralları", "local_tips"],
        ["Ramazan ayında dikkat edilecekler", "local_tips"],
        ["Türk misafirperverliği nasıl karşılanır", "local_tips"],
        ["Hamam kültürü ilk kez gidecekler için", "local_tips"],
        ["El öpme geleneği ne zaman uygulanır", "local_tips"],
        ["Mosque visit dress code", "local_tips"],
        ["Ramadan month precautions", "local_tips"],
        ["Turkish hospitality response", "local_tips"],
        ["Hammam culture for first-timers", "local_tips"],
        ["Hand-kissing tradition when to apply", "local_tips"],
        ["Çay ikramı nasıl cevaplanır", "local_tips"],
        ["Nazar boncuğu geleneği", "local_tips"],
        ["Türk kahvesi falı nasıl okunur", "local_tips"],
        ["Bayram ziyareti görgü kuralları", "local_tips"],
        ["Sokak selamlaşma kültürü", "local_tips"],
        ["How to respond to tea offer", "local_tips"],
        ["Evil eye bead tradition", "local_tips"],
        ["Turkish coffee fortune reading", "local_tips"],
        ["Holiday visit etiquette", "local_tips"],
        ["Street greeting culture", "local_tips"],
        ["Fotoğraf çekerken dikkat edilecekler", "local_tips"],
        ["Yerel halka soru sorma şekli", "local_tips"],
        ["Pazarlık yaparken davranış", "local_tips"],
        ["Resmi yerler ziyaret kuralları", "local_tips"],
        ["Trafik kuralları yaya geçidi", "local_tips"],
        ["Photo taking precautions", "local_tips"],
        ["How to ask locals questions", "local_tips"],
        ["Behavior while bargaining", "local_tips"],
        ["Official places visit rules", "local_tips"],
        ["Traffic rules pedestrian crossing", "local_tips"],
        ["Taksi sürücüleriyle iletişim", "local_tips"],
        ["Tipping culture in Istanbul", "local_tips"],
        ["Restaurant bill splitting", "local_tips"],
        ["Smoking regulations where", "local_tips"],
        ["Queue culture Turkish style", "local_tips"],
        ["Taxi driver communication", "local_tips"],
        ["Bahşiş kültürü İstanbul'da", "local_tips"],
        ["Restoran hesabı bölme", "local_tips"],
        ["Sigara içme kuralları nerede", "local_tips"],
        ["Sıra kültürü Türk tarzı", "local_tips"],
        
        # Safety & practical tips (40 samples)
        ["Güvenli mahalleler hangileri", "local_tips"],
        ["Gece dışarı çıkma güvenliği", "local_tips"],
        ["Değerli eşya saklama önerileri", "local_tips"],
        ["Telefon şarj noktaları nerede", "local_tips"],
        ["Ücretsiz wifi mekanları", "local_tips"],
        ["Safe neighborhoods which ones", "local_tips"],
        ["Night out safety tips", "local_tips"],
        ["Valuable items storage advice", "local_tips"],
        ["Phone charging spots where", "local_tips"],
        ["Free wifi locations", "local_tips"],
        ["ATM kullanma güvenliği", "local_tips"],
        ["Turistik dolandırıcılık şemaları", "local_tips"],
        ["Kaybolunca ne yapılmalı", "local_tips"],
        ["Acil durum numaraları", "local_tips"],
        ["Pasaport kaybı prosedürü", "local_tips"],
        ["ATM usage safety", "local_tips"],
        ["Tourist scam schemes", "local_tips"],
        ["What to do if lost", "local_tips"],
        ["Emergency numbers Istanbul", "local_tips"],
        ["Passport loss procedure", "local_tips"],
        ["Su içme güvenliği musluk suyu", "local_tips"],
        ["İlaç bulma nöbetçi eczane", "local_tips"],
        ["Hastalandığımda nereye gitmeli", "local_tips"],
        ["Polis yardımı nasıl çağrılır", "local_tips"],
        ["Elçilik konsolosluk bilgileri", "local_tips"],
        ["Tap water safety for drinking", "local_tips"],
        ["Finding medicine duty pharmacy", "local_tips"],
        ["Where to go when sick", "local_tips"],
        ["How to call police help", "local_tips"],
        ["Embassy consulate information", "local_tips"],
        ["Çanta gasp tehlikesi yerler", "local_tips"],
        ["Güvenli para bozma yerleri", "local_tips"],
        ["Otel kasası güvenilir mi", "local_tips"],
        ["Kalabalık yerlerde dikkat", "local_tips"],
        ["Gece tek başına güvenli mi", "local_tips"],
        ["Bag snatch danger zones", "local_tips"],
        ["Safe money exchange places", "local_tips"],
        ["Hotel safe reliability", "local_tips"],
        ["Crowded places precautions", "local_tips"],
        ["Alone at night safety", "local_tips"],
    ]


def get_new_hidden_gems_samples():
    """100+ samples for Hidden Gems intent"""
    return [
        # Off-the-beaten-path locations (30 samples)
        ["Turistlerin bilmediği yerler", "hidden_gems"],
        ["Gizli bahçeler İstanbul", "hidden_gems"],
        ["Yerel halkın gittiği mekanlar", "hidden_gems"],
        ["Saklı kalmış tarihi yerler", "hidden_gems"],
        ["Bilinmeyen seyir terasları", "hidden_gems"],
        ["Places tourists don't know", "hidden_gems"],
        ["Secret gardens Istanbul", "hidden_gems"],
        ["Where locals actually go", "hidden_gems"],
        ["Hidden historical sites", "hidden_gems"],
        ["Unknown viewpoints", "hidden_gems"],
        ["Balat'ta gizli kafeler", "hidden_gems"],
        ["Kadıköy arka sokaklarda keşif", "hidden_gems"],
        ["Üsküdar'da bilinmeyen mekanlar", "hidden_gems"],
        ["Cihangir gizli restoranları", "hidden_gems"],
        ["Moda'da saklı kalanlar", "hidden_gems"],
        ["Hidden cafes in Balat", "hidden_gems"],
        ["Kadikoy backstreet discoveries", "hidden_gems"],
        ["Unknown spots in Uskudar", "hidden_gems"],
        ["Cihangir secret restaurants", "hidden_gems"],
        ["Hidden places in Moda", "hidden_gems"],
        ["Fener Rum Patrikhanesi yakını gezilecek", "hidden_gems"],
        ["Yedikule surları altında ne var", "hidden_gems"],
        ["Pierre Loti'nin gizli alternatifi", "hidden_gems"],
        ["Çamlıca'da bilinmeyen noktalar", "hidden_gems"],
        ["Polonezköy saklı yerleri", "hidden_gems"],
        ["Near Fener Greek Patriarchate what to see", "hidden_gems"],
        ["Under Yedikule walls what's there", "hidden_gems"],
        ["Pierre Loti secret alternative", "hidden_gems"],
        ["Unknown spots in Camlica", "hidden_gems"],
        ["Polonezkoy hidden places", "hidden_gems"],
        
        # Hidden food spots (25 samples)
        ["Yerel halkın bildiği lokantalar", "hidden_gems"],
        ["Turistik olmayan balık restoranları", "hidden_gems"],
        ["Gizli kahvaltı mekanları", "hidden_gems"],
        ["Saklı kalmış tatlıcılar", "hidden_gems"],
        ["Arka sokak kebapçıları", "hidden_gems"],
        ["Restaurants only locals know", "hidden_gems"],
        ["Non-touristy fish restaurants", "hidden_gems"],
        ["Secret breakfast spots", "hidden_gems"],
        ["Hidden dessert shops", "hidden_gems"],
        ["Backstreet kebab places", "hidden_gems"],
        ["Tarihi esnaf lokantaları", "hidden_gems"],
        ["Kumkapı'nın gerçek mekanları", "hidden_gems"],
        ["Karaköy'de yerel mantı yeri", "hidden_gems"],
        ["Beşiktaş'ta gizli börekçi", "hidden_gems"],
        ["Fatih'te orijinal çorbacı", "hidden_gems"],
        ["Historic artisan restaurants", "hidden_gems"],
        ["Real places in Kumkapi", "hidden_gems"],
        ["Local manti place in Karakoy", "hidden_gems"],
        ["Hidden borek shop in Besiktas", "hidden_gems"],
        ["Original soup restaurant in Fatih", "hidden_gems"],
        ["Kadıköy çarşı içi köfteci", "hidden_gems"],
        ["Beyoğlu arka sokaklarda meyhane", "hidden_gems"],
        ["Eminönü'nde yerel pideci", "hidden_gems"],
        ["Kuzguncuk'ta gizli kafe", "hidden_gems"],
        ["Arnavutköy'de arka plan restoranları", "hidden_gems"],
        
        # Hidden cultural spots (25 samples)
        ["Bilinmeyen küçük müzeler", "hidden_gems"],
        ["Gizli sanat galerileri", "hidden_gems"],
        ["Yerel sanatçı atölyeleri", "hidden_gems"],
        ["Saklı kitap kafeleri", "hidden_gems"],
        ["Alternatif kültür mekanları", "hidden_gems"],
        ["Unknown small museums", "hidden_gems"],
        ["Secret art galleries", "hidden_gems"],
        ["Local artist workshops", "hidden_gems"],
        ["Hidden book cafes", "hidden_gems"],
        ["Alternative culture venues", "hidden_gems"],
        ["Beyoğlu'nda indie sinema", "hidden_gems"],
        ["Kadıköy underground müzik mekanları", "hidden_gems"],
        ["Vintage dükkanları gizli", "hidden_gems"],
        ["Yerel tiyatro sahneleri", "hidden_gems"],
        ["Alternatif sergi alanları", "hidden_gems"],
        ["Indie cinema in Beyoglu", "hidden_gems"],
        ["Underground music venues Kadikoy", "hidden_gems"],
        ["Secret vintage shops", "hidden_gems"],
        ["Local theater stages", "hidden_gems"],
        ["Alternative exhibition spaces", "hidden_gems"],
        ["Cihangir sanat atölyeleri", "hidden_gems"],
        ["Karaköy sanatçı mekânları", "hidden_gems"],
        ["Galata'da gizli konser salonları", "hidden_gems"],
        ["Nişantaşı arkası galeri", "hidden_gems"],
        ["Şişli antika dükkânları", "hidden_gems"],
        
        # Hidden nature spots (20 samples)
        ["Gizli parklar İstanbul", "hidden_gems"],
        ["Bilinmeyen piknik alanları", "hidden_gems"],
        ["Saklı yürüyüş rotaları", "hidden_gems"],
        ["Yerel halkın gittiği plajlar", "hidden_gems"],
        ["Şehir içi doğa kaçamakları", "hidden_gems"],
        ["Secret parks Istanbul", "hidden_gems"],
        ["Unknown picnic areas", "hidden_gems"],
        ["Hidden walking routes", "hidden_gems"],
        ["Beaches where locals go", "hidden_gems"],
        ["Urban nature escapes", "hidden_gems"],
        ["Belgrad Ormanı gizli yolları", "hidden_gems"],
        ["Çamlıca'da bilinmeyen patikalar", "hidden_gems"],
        ["Boğaz kıyısında saklı koylar", "hidden_gems"],
        ["Adalar'da yerel plajları", "hidden_gems"],
        ["Emirgan Korusu gizli köşeleri", "hidden_gems"],
        ["Belgrade Forest secret paths", "hidden_gems"],
        ["Unknown trails in Camlica", "hidden_gems"],
        ["Hidden coves along Bosphorus", "hidden_gems"],
        ["Local beaches in Islands", "hidden_gems"],
        ["Emirgan Grove secret corners", "hidden_gems"],
    ]


def get_new_events_samples():
    """150+ samples for Events intent"""
    return [
        # Festivals & celebrations (30 samples)
        ["Bu hafta hangi festivaller var", "events"],
        ["İstanbul müzik festivali tarihleri", "events"],
        ["Film festivali ne zaman", "events"],
        ["Ramazan etkinlikleri nerede", "events"],
        ["Yılbaşı kutlamaları mekanlar", "events"],
        ["What festivals this week", "events"],
        ["Istanbul music festival dates", "events"],
        ["When is film festival", "events"],
        ["Ramadan events where", "events"],
        ["New Year celebrations venues", "events"],
        ["Caz festivali bilet fiyatları", "events"],
        ["Bienal sergileri ne zaman", "events"],
        ["Tiyatro festivali programı", "events"],
        ["Dans gösterileri bu ay", "events"],
        ["Klasik müzik konserleri yakında", "events"],
        ["Jazz festival ticket prices", "events"],
        ["Biennial exhibitions when", "events"],
        ["Theater festival program", "events"],
        ["Dance shows this month", "events"],
        ["Classical concerts upcoming", "events"],
        ["Gastronomi festivali lokasyonları", "events"],
        ["Kitap fuarı ne zaman açılıyor", "events"],
        ["Sanat bienali mekanları", "events"],
        ["Çocuk festivalleri bugün", "events"],
        ["Kültür sanat etkinlikleri hafta sonu", "events"],
        ["Gastronomy festival locations", "events"],
        ["When does book fair open", "events"],
        ["Art biennial venues", "events"],
        ["Children festivals today", "events"],
        ["Culture art events weekend", "events"],
        
        # Concerts & performances (30 samples)
        ["Bu akşam konser var mı", "events"],
        ["Canlı müzik mekanları güncel", "events"],
        ["Opera gösterileri bu hafta", "events"],
        ["Bale performansları yaklaşan", "events"],
        ["Stand-up gösterileri nerede", "events"],
        ["Concert tonight anywhere", "events"],
        ["Live music venues current", "events"],
        ["Opera shows this week", "events"],
        ["Ballet performances upcoming", "events"],
        ["Stand-up shows where", "events"],
        ["Rock konserleri bu ay", "events"],
        ["Pop yıldızı konserleri", "events"],
        ["Türk sanat müziği etkinlikleri", "events"],
        ["DJ performansları gece", "events"],
        ["Akustik konserler hafta sonu", "events"],
        ["Rock concerts this month", "events"],
        ["Pop star concerts", "events"],
        ["Turkish classical music events", "events"],
        ["DJ performances tonight", "events"],
        ["Acoustic concerts weekend", "events"],
        ["Senfoni orkestrası programı", "events"],
        ["Chamber music performances", "events"],
        ["World music concerts", "events"],
        ["Electronic music events", "events"],
        ["Traditional music nights", "events"],
        ["Senfoni orkestrası programı", "events"],
        ["Oda müziği performansları", "events"],
        ["Dünya müziği konserleri", "events"],
        ["Elektronik müzik etkinlikleri", "events"],
        ["Geleneksel müzik geceleri", "events"],
        
        # Sports events (25 samples)
        ["Futbol maçları bu hafta sonu", "events"],
        ["Basketbol maçı biletleri", "events"],
        ["Maraton etkinlikleri İstanbul", "events"],
        ["Spor müsabakaları yakında", "events"],
        ["Voleybol turnuvası ne zaman", "events"],
        ["Football matches this weekend", "events"],
        ["Basketball game tickets", "events"],
        ["Marathon events Istanbul", "events"],
        ["Sports competitions upcoming", "events"],
        ["Volleyball tournament when", "events"],
        ["Formula 1 İstanbul tarihi", "events"],
        ["Bisiklet yarışı rotası", "events"],
        ["Koşu etkinlikleri bu ay", "events"],
        ["Yoga festivali nerede", "events"],
        ["Outdoor sports events", "events"],
        ["Formula 1 Istanbul date", "events"],
        ["Cycling race route", "events"],
        ["Running events this month", "events"],
        ["Yoga festival where", "events"],
        ["Açık hava spor etkinlikleri", "events"],
        ["Yüzme yarışmaları", "events"],
        ["Tenis turnuvaları", "events"],
        ["Ekstrem sporlar gösterileri", "events"],
        ["E-spor turnuvaları", "events"],
        ["Fitness etkinlikleri", "events"],
        
        # Cultural events (30 samples)
        ["Sergi açılışları bu hafta", "events"],
        ["Müze geceleri ne zaman", "events"],
        ["Kültür sanat etkinlikleri", "events"],
        ["Workshop atölyeler yakında", "events"],
        ["Konferans ve seminerler", "events"],
        ["Exhibition openings this week", "events"],
        ["Museum nights when", "events"],
        ["Cultural art events", "events"],
        ["Workshops upcoming", "events"],
        ["Conferences and seminars", "events"],
        ["Sanat galerisi açılışları", "events"],
        ["Fotoğraf sergisi nerede", "events"],
        ["Heykel sergileri güncel", "events"],
        ["Modern sanat etkinlikleri", "events"],
        ["Dijital sanat gösterileri", "events"],
        ["Art gallery openings", "events"],
        ["Photography exhibition where", "events"],
        ["Sculpture exhibitions current", "events"],
        ["Modern art events", "events"],
        ["Digital art shows", "events"],
        ["Tarih konferansları", "events"],
        ["Edebiyat söyleşileri", "events"],
        ["Mimarlık sergisi", "events"],
        ["Film gösterimleri özel", "events"],
        ["Documentary screenings", "events"],
        ["History conferences", "events"],
        ["Literature talks", "events"],
        ["Architecture exhibition", "events"],
        ["Special film screenings", "events"],
        ["Belgesel gösterimleri", "events"],
        
        # Seasonal events (35 samples)
        ["Lale festivali ne zaman", "events"],
        ["Yılbaşı etkinlikleri listesi", "events"],
        ["Ramazan etkinlik takvimi", "events"],
        ["Yaz açık hava konserleri", "events"],
        ["Kış festivali programı", "events"],
        ["Tulip festival when", "events"],
        ["New Year events list", "events"],
        ["Ramadan event calendar", "events"],
        ["Summer outdoor concerts", "events"],
        ["Winter festival program", "events"],
        ["Bahar festivalleri", "events"],
        ["Sonbahar etkinlikleri", "events"],
        ["Kurban Bayramı programları", "events"],
        ["23 Nisan çocuk şenlikleri", "events"],
        ["29 Ekim kutlamaları", "events"],
        ["Spring festivals", "events"],
        ["Autumn events", "events"],
        ["Eid al-Adha programs", "events"],
        ["April 23 children festivities", "events"],
        ["October 29 celebrations", "events"],
        ["Cadılar bayramı etkinlikleri", "events"],
        ["Sevgililer günü özel geceler", "events"],
        ["Noel pazarları", "events"],
        ["Hıdrellez şenlikleri", "events"],
        ["Nevruz etkinlikleri", "events"],
        ["Halloween events", "events"],
        ["Valentine's Day special nights", "events"],
        ["Christmas markets", "events"],
        ["Hidrellez festivities", "events"],
        ["Nowruz events", "events"],
        ["Boğaz'da yaz konserleri", "events"],
        ["Kış bahçesi etkinlikleri", "events"],
        ["Plaj partileri yaz", "events"],
        ["Kayak festivali", "events"],
        ["Deniz festivali", "events"],
    ]


def get_new_neighborhoods_samples():
    """100+ samples for new Neighborhoods intent"""
    return [
        # Neighborhood characteristics (25 samples)
        ["Kadıköy nasıl bir semt", "neighborhoods"],
        ["Beşiktaş'ın özellikleri neler", "neighborhoods"],
        ["Beyoğlu hakkında bilgi", "neighborhoods"],
        ["Sultanahmet semti nasıl", "neighborhoods"],
        ["Üsküdar'da yaşam nasıl", "neighborhoods"],
        ["What is Kadikoy neighborhood like", "neighborhoods"],
        ["Besiktas characteristics what", "neighborhoods"],
        ["Information about Beyoglu", "neighborhoods"],
        ["How is Sultanahmet district", "neighborhoods"],
        ["Life in Uskudar how", "neighborhoods"],
        ["Cihangir semtinin havası", "neighborhoods"],
        ["Moda'nın özellikle", "neighborhoods"],
        ["Nişantaşı ne tür bir yer", "neighborhoods"],
        ["Ortaköy'ün karakteri", "neighborhoods"],
        ["Balat semti nasıl değişti", "neighborhoods"],
        ["Cihangir neighborhood vibe", "neighborhoods"],
        ["Moda's characteristics", "neighborhoods"],
        ["What kind of place is Nisantasi", "neighborhoods"],
        ["Ortakoy's character", "neighborhoods"],
        ["How Balat district changed", "neighborhoods"],
        ["Arnavutköy tarihi dokusu", "neighborhoods"],
        ["Kuzguncuk'un hikayesi", "neighborhoods"],
        ["Fener Balat kültürü", "neighborhoods"],
        ["Bebek semtinin tarihi", "neighborhoods"],
        ["Etiler'in özellikleri", "neighborhoods"],
        
        # Neighborhood comparisons (20 samples)
        ["Kadıköy mi Beşiktaş mı", "neighborhoods"],
        ["Sultanahmet vs Beyoğlu", "neighborhoods"],
        ["Cihangir ile Galata farkı", "neighborhoods"],
        ["Moda veya Nişantaşı", "neighborhoods"],
        ["En yaşanası semt hangisi", "neighborhoods"],
        ["Kadikoy or Besiktas which", "neighborhoods"],
        ["Sultanahmet vs Beyoglu", "neighborhoods"],
        ["Difference Cihangir and Galata", "neighborhoods"],
        ["Moda or Nisantasi", "neighborhoods"],
        ["Most livable district which", "neighborhoods"],
        ["Gentrleşen semtler hangileri", "neighborhoods"],
        ["Eski doku korunan yerler", "neighborhoods"],
        ["Modern vs tarihi semtler", "neighborhoods"],
        ["Sakin semtler hangileri", "neighborhoods"],
        ["Hareketli muhitler nerede", "neighborhoods"],
        ["Gentrified districts which", "neighborhoods"],
        ["Old texture preserved places", "neighborhoods"],
        ["Modern vs historical districts", "neighborhoods"],
        ["Quiet neighborhoods which", "neighborhoods"],
        ["Lively areas where", "neighborhoods"],
        
        # Neighborhood activities (25 samples)
        ["Kadıköy'de ne yapılır", "neighborhoods"],
        ["Beşiktaş'ta gezilecek", "neighborhoods"],
        ["Beyoğlu'nda yapılacaklar", "neighborhoods"],
        ["Sultanahmet'te görülmesi gerekenler", "neighborhoods"],
        ["Üsküdar'da ne görülür", "neighborhoods"],
        ["What to do in Kadikoy", "neighborhoods"],
        ["Places to visit Besiktas", "neighborhoods"],
        ["Things to do Beyoglu", "neighborhoods"],
        ["Must-sees in Sultanahmet", "neighborhoods"],
        ["What to see Uskudar", "neighborhoods"],
        ["Cihangir'de kafe gezisi", "neighborhoods"],
        ["Moda'da yürüyüş rotası", "neighborhoods"],
        ["Nişantaşı'nda alışveriş", "neighborhoods"],
        ["Ortaköy'de ne yenir", "neighborhoods"],
        ["Balat'ta fotoğraf rotası", "neighborhoods"],
        ["Cafe tour in Cihangir", "neighborhoods"],
        ["Walking route in Moda", "neighborhoods"],
        ["Shopping in Nisantasi", "neighborhoods"],
        ["What to eat Ortakoy", "neighborhoods"],
        ["Photo route in Balat", "neighborhoods"],
        ["Arnavutköy'de balık yemek", "neighborhoods"],
        ["Kuzguncuk'ta tarihi evler", "neighborhoods"],
        ["Fener'de kilise turu", "neighborhoods"],
        ["Bebek'te sahil yürüyüşü", "neighborhoods"],
        ["Etiler'de gece hayatı", "neighborhoods"],
        
        # Neighborhood recommendations (30 samples)
        ["Gençlere uygun semtler", "neighborhoods"],
        ["Ailelere özel muhitler", "neighborhoods"],
        ["Sanatçıların semti neresi", "neighborhoods"],
        ["Öğrenciler için ideal yerler", "neighborhoods"],
        ["Lüks semtler hangileri", "neighborhoods"],
        ["Neighborhoods for young people", "neighborhoods"],
        ["Family-friendly districts", "neighborhoods"],
        ["Artists neighborhood where", "neighborhoods"],
        ["Ideal places for students", "neighborhoods"],
        ["Luxury districts which", "neighborhoods"],
        ["Ekonomik semtler", "neighborhoods"],
        ["Hipster mahalleler", "neighborhoods"],
        ["Alternatif kültür semtleri", "neighborhoods"],
        ["Muhafazakar semtler", "neighborhoods"],
        ["Kozmopolit yerler", "neighborhoods"],
        ["Budget-friendly neighborhoods", "neighborhoods"],
        ["Hipster districts", "neighborhoods"],
        ["Alternative culture neighborhoods", "neighborhoods"],
        ["Conservative districts", "neighborhoods"],
        ["Cosmopolitan places", "neighborhoods"],
        ["Yabancıların çok olduğu semtler", "neighborhoods"],
        ["Türk mahalle kültürü nerede", "neighborhoods"],
        ["Bohem semtler", "neighborhoods"],
        ["İş merkezi semtler", "neighborhoods"],
        ["Deniz kenarı semtler", "neighborhoods"],
        ["Districts with many expats", "neighborhoods"],
        ["Turkish neighborhood culture where", "neighborhoods"],
        ["Bohemian districts", "neighborhoods"],
        ["Business center neighborhoods", "neighborhoods"],
        ["Seaside districts", "neighborhoods"],
    ]


def add_training_data():
    """Add all new training samples to the comprehensive dataset"""
    
    # Load existing data
    data_file = Path("comprehensive_training_data.json")
    with open(data_file, "r", encoding="utf-8") as f:
        existing_data = json.load(f)
    
    print(f"📊 Current dataset: {len(existing_data)} samples")
    
    # Count existing intents
    intent_counts = Counter([item[1] for item in existing_data])
    print(f"   - local_tips: {intent_counts.get('local_tips', 0)}")
    print(f"   - hidden_gems: {intent_counts.get('hidden_gems', 0)}")
    print(f"   - events: {intent_counts.get('events', 0)}")
    print(f"   - neighborhoods: {intent_counts.get('neighborhoods', 0)}")
    
    # Collect new samples
    new_samples = []
    new_samples.extend(get_new_local_tips_samples())
    new_samples.extend(get_new_hidden_gems_samples())
    new_samples.extend(get_new_events_samples())
    new_samples.extend(get_new_neighborhoods_samples())
    
    print(f"\n📝 Adding {len(new_samples)} new samples:")
    new_intent_counts = Counter([item[1] for item in new_samples])
    for intent, count in sorted(new_intent_counts.items()):
        print(f"   + {intent}: {count} samples")
    
    # Combine and save
    combined_data = existing_data + new_samples
    
    # Create backup
    backup_file = data_file.with_suffix('.backup.json')
    with open(backup_file, "w", encoding="utf-8") as f:
        json.dump(existing_data, f, ensure_ascii=False, indent=2)
    print(f"\n💾 Backup created: {backup_file}")
    
    # Save updated data
    with open(data_file, "w", encoding="utf-8") as f:
        json.dump(combined_data, f, ensure_ascii=False, indent=2)
    
    print(f"\n✅ Updated dataset: {len(combined_data)} samples")
    
    # Show final distribution
    final_counts = Counter([item[1] for item in combined_data])
    print(f"\n📊 Final intent distribution:")
    for intent, count in sorted(final_counts.items(), key=lambda x: x[1], reverse=True):
        print(f"   {intent:30s} {count:4d} samples")
    
    print(f"\n🎉 Training data enhancement complete!")
    print(f"   Total samples: {len(existing_data)} → {len(combined_data)}")
    print(f"   Added: {len(new_samples)} new samples")


if __name__ == "__main__":
    add_training_data()
